### ISSUE TITLE
[BUG] Caractères spéciaux non reconnus

### ISSUE THREAD

**Issue by nicodsi78** [spoutnik911/DactyloLibre-CsharpVersion#1]
**Description du bug**
Les caractéres spéciaux tels que { & } ne sont pas reconnus lors de la frappe

**Information de l'ordinateur**
 - WIndows 10

**Comment by spoutnik911** [comment]
> **Description du bug**
> Les caractéres spéciaux tels que { & } ne sont pas reconnus lors de la frappe
> 
> **Information de l'ordinateur**
> 
>     * WIndows 10

Pourrais-je avoir un screenshot ? Pour ma part, le logiciel ne montre pas cette erreur avec la version [Alpha 1.0](https://github.com/spoutnik911/DactyloLibre-CsharpVersion/releases/tag/1.0)

- à noter qu'il faut taper dans la zone de texte sur le rectangle gris central en bas à gauche pour pouvoir écrire
![zonedefrappe](https://user-images.githubusercontent.com/34311347/93718620-c43c6e80-fb7d-11ea-9686-5b5685b8d422.png)



![itwork](https://user-images.githubusercontent.com/34311347/93718471-d9fd6400-fb7c-11ea-8542-c50c2be0c9b9.png)

**Comment by nicodsi78** [comment]
Je viens de me rendre compte qu'il y avait un espace... Du coup oublie c'est juste moi qui ai pas vu un espace 
Sur le screen je trouve on dirait qu'il attend un {

![image](https://user-images.githubusercontent.com/71605362/93718738-53498680-fb7e-11ea-8a67-cbfb795f0f69.png)

**Comment by spoutnik911** [comment]
Pourquoi y a t-il du code dans ton programme ? 😱 😨

**Comment by nicodsi78** [comment]
Yep exactement, mais j'avais pas vu, j'ai essayé pendant 5 min ça marchait pas x)
C'est juste un fichier que j'ai chargé qui contient du code. Je sais même plus pourquoi x)
