### ISSUE TITLE
[Suggestion] Bouton stop !

### ISSUE THREAD

**Issue by nicodsi78** [spoutnik911/DactyloLibre-CsharpVersion#2]
**Amélioration par rapport à un problème ?**
[*] Oui
[] Non
(mettre l'étoile dans la case correspondante)
- Explication du problème

Il n'y a pas de bouton stop sur le programme, il faut le redémarrer

**Description de ce que vous aimeriez**

Un bouton stop ou redemarrer pour relancer le soft sans devoir le fermer

**Comment by spoutnik911** [comment]
> **Description de ce que vous aimeriez**
> Un` bouton stop ou redemarrer pour relancer le soft sans devoir le fermer

Il faut que j'y réfléchisse, mettre sur pause implique que tu puisses tricher sur le temps, non ?
Pour ce qui est du bouton stop, je pense que je vais l'ajouter dans la prochaine version.
Merci beaucoup ! 👍

**Comment by spoutnik911** [comment]
Bouton stop ajouté 😄
